version: '3.7'
services:
    source_postgres:
      image: postgres:10.5
      restart: always
      environment: 
        - POSTGRES_DB=warehouse
        - POSTGRES_USER=meltano
        - POSTGRES_PASSWORD=meltano
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
        - ./postgres-data/source:/var/lib/postgresql/data